server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://root:RyymeFSAsWAAMlECNUYlmuocXxvaymWo@shinkansen.proxy.rlwy.net:55341/railway"
    username: root
    password: RyymeFSAsWAAMlECNUYlmuocXxvaymWo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: trungtamquanlysktxptit@gmail.com
    password: hucladfswqalfqil
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  signerKey: "t1trmjezOQeXQVCLe58ant1iLOnVdDhwR/CRrmevOI77vsOi5zzFDnMPaHLLm5/AdwJHjavnBBr2vQoBAv96Dg=="
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
  expiration: 86400000

cloudinary:
  cloud-name: "dxxswaeor"
  api-key: "556294491589589"
  api-secret: "zvVZjk0lyAOUUMXczSJzVt6IHwo"

open:
  api:
    title: API document
    version: v1.0.0
    description: Mota API service
    serverUrl: http://localhost:8080
    serverName: server test
